blank_issues_enabled: true

contact_links:
  - name: 質問・ヘルプ / Question / Help
    url: https://github.com/Rx-K8/AnotherMe-TTS-Server/discussions
    about: |
      質問やヘルプが必要な場合は、GitHub Discussions をご利用ください。
      For questions or help, please use GitHub Discussions.
