name: Lint Backend

on:
  push:
    branches:
      - main
    paths:
      - "app/**/*.py"
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
    paths:
      - "app/**/*.py"

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: false
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment-dev.yml
          activate-environment: anotherme_tts_dev
          auto-activate-base: false
      - name: Run lint
        run: bash scripts/lint.sh
